package taxes;
import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "taxcomparison2")
public class TaxCompObj implements Serializable{

  int wages;
  int homeInterest;
  int propertyTaxes;
  int stateTaxes;
  int otherDeductions;
  String postalCode;
  double savings;
  double owedTaxes17;
  double owedTaxes18;
  double effectiveRate17;
  double effectiveRate18;
  boolean married;
  String uid;


  public TaxCompObj(TaxRequest req, TaxResponse resp){
    this.wages = req.getWages();
    this.homeInterest = req.getHomeInterest();
    this.propertyTaxes = req.getPropertyTaxes();
    this.stateTaxes = req.getStateTaxes();
    this.otherDeductions = req.getOtherDeductions();
    this.postalCode = req.getPostalCode();
    this.savings = resp.getSavings();
    this.owedTaxes17 = resp.getOwedTaxes17();
    this.owedTaxes18 = resp.getOwedTaxes18();
    this.effectiveRate17 = resp.getEffectiveRate17();
    this.effectiveRate18 = resp.getEffectiveRate18();
    this.married = req.isMarried();
  }

  @DynamoDBHashKey(attributeName = "uid")
  @DynamoDBAutoGeneratedKey
  public String getUid() {
      return uid;
  }

  public void setOrderId(String uid) {
      this.uid = uid;
  }

  @DynamoDBAttribute(attributeName = "Wages")
  public int getWages() {
    return wages;
  }
  public void setWages(int wages) {
    this.wages = wages;
  }
  @DynamoDBAttribute(attributeName = "HomeInterest")
  public int getHomeInterest() {
    return homeInterest;
  }
  public void setHomeInterest(int homeInterest) {
    this.homeInterest = homeInterest;
  }
  @DynamoDBAttribute(attributeName = "PropertyTaxes")
  public int getPropertyTaxes() {
    return propertyTaxes;
  }
  public void setPropertyTaxes(int propertyTaxes) {
    this.propertyTaxes = propertyTaxes;
  }

  @DynamoDBAttribute(attributeName = "StateTaxes")
  public int getStateTaxes() {
    return stateTaxes;
  }
  public void setStateTaxes(int stateTaxes) {
    this.stateTaxes = stateTaxes;
  }
  @DynamoDBAttribute(attributeName = "OtherDeductions")
  public int getOtherDeductions() {
    return otherDeductions;
  }
  public void setOtherDeductions(int otherDeductions) {
    this.otherDeductions = otherDeductions;
  }
  @DynamoDBAttribute(attributeName = "PostalCode")
  public String getPostalCode() {
    return postalCode;
  }
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }
  @DynamoDBAttribute(attributeName = "Savings")
  public double getSavings() {
    return savings;
  }
  public void setSavings(double savings) {
    this.savings = savings;
  }
  @DynamoDBAttribute(attributeName = "OwedTaxes17")
  public double getOwedTaxes17() {
    return owedTaxes17;
  }
  public void setOwedTaxes17(double owedTaxes17) {
    this.owedTaxes17 = owedTaxes17;
  }
  @DynamoDBAttribute(attributeName = "OwedTaxes18")
  public double getOwedTaxes18() {
    return owedTaxes18;
  }
  public void setOwedTaxes18(double owedTaxes18) {
    this.owedTaxes18 = owedTaxes18;
  }
  @DynamoDBAttribute(attributeName = "EffectiveRate17")
  public double getEffectiveRate17() {
    return effectiveRate17;
  }

  public void setEffectiveRate17(double effectiveRate17) {
    this.effectiveRate17 = effectiveRate17;
  }
  @DynamoDBAttribute(attributeName = "EffectiveRate18")
  public double getEffectiveRate18() {
    return effectiveRate18;
  }
  public void setEffectiveRate18(double effectiveRate18) {
    this.effectiveRate18 = effectiveRate18;
  }
  @DynamoDBAttribute(attributeName = "Married")
  public boolean isMarried() {
    return married;
  }
  public void setMarried(boolean married) {
    this.married = married;
  }

}
